### ISSUE TITLE
v12.12 Adult Scraper Data disappears

### ISSUE THREAD

**Issue by CodyBerenson** [adultmm/AdultMediaManager#123]
Greetings,

Perhaps its just me.  When I install the latest version, whether as a fresh install or by replacing the Modules, all Adult scraper choices go away.  When I delete everything and download the previous version, 12.11, all of the adult scraper choices are visible.  It has been a long week.  Am I crazy?  LOL.  Thanks!  Here's the view with the latest version:
![image](https://github.com/user-attachments/assets/c0b57041-3a23-4081-b7d5-c30c27606ac7)

**Comment by adultmm** [comment]
Sorry, you're right. It works on my developer laptop but not on another PC. I'll fix it soon. Thanks.

**Comment by adultmm** [comment]
I was unable to resolve the DLL dependency issue between my plugin and AMM, so I released a [standalone version](https://github.com/adultmm/AdultMediaManager/releases/tag/v1.0.0-beta1). Please try it out and let me know what you experience.

**Comment by CodyBerenson** [comment]
Hello! Thanks for all that you're doing.  

1.  at 98% extract, the installer failed.  I was able to unrar the installer with no error.
2.   Still getting 403 errors for IAFD.  Log attached.

[2024-07-21.csv](https://github.com/user-attachments/files/16323274/2024-07-21.csv)

![image](https://github.com/user-attachments/assets/3209321d-f453-4ea3-adb4-cd150f82370c)

![image](https://github.com/user-attachments/assets/28fb94de-e3d8-4d33-9ffc-3c2b2a3924b7)

**Comment by adultmm** [comment]
Hi Cody, Thanks for your feedback. At this point, I have no more ideas on how to fix the IAFD Scraper for you. I tried it on four remote desktops from different countries, and it worked. I'm thinking about what else I can do. I'm closing this issue, but the [IAFD 403 Forbidden Error](https://github.com/adultmm/AdultMediaManager/issues/121) will remain open until the problem is resolved.
